### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by abhishekgupta92** [navgurukul/lennon#10]
WRITE A BETTER README 📦 

* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository

**Comment by RishabhVerma** [comment]
@abhishekgupta92 It'll be helpful if you can write the major sections which should be added.

Few things I can think of:

1. How does it interact with the API?
2. The git workflow we should follow
3. Any special things to set up the project

What else?

**Comment by RishabhVerma** [comment]
Also add the google drive link to the wireframes folder in README for easy access.

**Comment by abhishekgupta92** [comment]
Only Vidur is working on this. We will document this whenever we have more
people.

--
P.S. Global warming is not cool! Save paper, save earth :)

**Comment by abhishekgupta92** [comment]
Makes sense. will do :) Where have you uploaded the wireframe, I couldn't
find it.

--
P.S. Global warming is not cool! Save paper, save earth :)

**Comment by vidur149** [comment]
I haven't uploaded the wireframe on google drive. cc @abhishekgupta92 
I still dont have the updated wireframe :/

**Comment by RishabhVerma** [comment]
@vidur149 Here is the link: https://drive.google.com/drive/folders/0B1XBdeTOOHL3Rjg2WHhZMS11d28?usp=sharing

Add it :)
