### ISSUE TITLE
Add the student report view after the API for the same has been added in Galileo

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/lennon#17]
Check the attached file for the screen being talked about.

<img width="1323" alt="screen shot 2017-07-01 at 6 08 23 pm" src="https://user-images.githubusercontent.com/933896/27762105-564b08ea-5e88-11e7-9548-fb7a13666dde.png">

**Comment by vidur149** [comment]
Completed the API, also completed the component.
