### ISSUE TITLE
Course Tiles Component

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/lennon#3]
Three kinds of tiles should be supported:

1. Courses user is facilitating
2. Courses user is enrolled under
3. Courses available to the user.

<img width="1378" alt="screen shot 2017-04-10 at 5 04 07 pm" src="https://cloud.githubusercontent.com/assets/933896/24859784/bdc6ade4-1e0f-11e7-8f6c-55ce1a6e8f2a.png">

**Comment by vidur149** [comment]
need and end point to find out the sequence number of last submitted assignment by the user so that i can add the progress component.
