### ISSUE TITLE
Detailed Course Viewing Page

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/lennon#5]
1. The notes section which can be reached using the `Dekho` button has to be implemented with this.
2. Solution submission needs to be implemented with this too.
3. The exercise Tree in the right bar also needs to be implemented with this.
4. Includes the `Aapka Progress` box too.
5. This also includes the enroll option.

*Does not include the report which can be seen using `Apne batch ka progress dekho`*

Check out the different views to show the submitted assignments on this page itself.

<img width="1107" alt="screen shot 2017-04-10 at 5 06 32 pm" src="https://cloud.githubusercontent.com/assets/933896/24859958/13a90270-1e10-11e7-9843-242816ca2e92.png">

**Comment by vidur149** [comment]
Backend is returning 2 states of a particular assignment i.e. completed true or fales, but we decided that there will be 4 states of an assignment. @RishabhVerma

**Comment by vidur149** [comment]
I dont what data do I have to display in aapka progress box. @RishabhVerma

**Comment by vidur149** [comment]
@RishabhVerma I need the wireframe for the enroll option.
