### ISSUE TITLE
Grid Report View

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/lennon#6]
Grid view to see overall progress of a certain batch.

<img width="646" alt="screen shot 2017-04-10 at 5 10 44 pm" src="https://cloud.githubusercontent.com/assets/933896/24860103/a8969fb4-1e10-11e7-8bfc-4c191fd545bc.png">

**Comment by vidur149** [comment]
=> Will this page be course specific or holistic ?
=> Need an end-point that will return list of assignments submitted by a student in a particular course.
or an end-point that will return all the assignments submitted by students in a given course. @RishabhVerma
