### ISSUE TITLE
Logout Feature

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/lennon#8]
Make the dreaded Google web sign-in logout work.

**Comment by vidur149** [comment]
logout button is working but an error in console is coming which says that gapi has been initialised twice.

**Comment by RishabhVerma** [comment]
Okay. This is not priority let's get done with the error issues before completing this.

**Comment by abhishekgupta92** [comment]
@vidur149 let's review this on a call whenever you are free.

**Comment by vidur149** [comment]
The logout feature sometimes work when we are not using incognito mode but never works when we signin  from the incognito window.
